### ISSUE TITLE
Support for error percentage?

### ISSUE THREAD

**Issue by smitchelus** [Shopify/semian#93]
Hi guys, love the library, but I wanted to see if you would be open/interested in adding support for error percent in addition to the current absolute error threshold? I find dealing with error rates in terms of percentages much more flexible than absolute values. If you're open to it I would be interested in trying to tackle it and send you a pull request. However, I don't want to maintain a fork of the project, so only want to go down this path if it is likely to get integrated back into the main code line.

**Comment by Sirupsen** [comment]
The percentage would have to be over some sliding window of requests, wouldn't you have to configure the size of that window based on time or absolute size?

**Comment by smitchelus** [comment]
Agreed, if I'm understanding the current code there's already a SlidingWindow used for tracking errors so I would imagine that we'd have to track the number of requests utilizing the same window so that we could do the proper comparison. Plenty of details to work out, but not work figuring out unless it would be considered generally useful.

**Comment by Sirupsen** [comment]
Honestly, I'm not sure this is worth it. I actually think it's harder to reason about errors in a window than it is for absolute errors in a row, and in our experience this has worked well. If you'd like to contribute, a huge, huge improvement to Semian would be a way to share the circuit breakers between processes in an IPC namespace. A SysV implementation of the circuit breaker using shared memory would be a massive improvement.

**Comment by smitchelus** [comment]
Strange, I don't think it sounds that hard to reason about (assuming we expose the right information). However, I'll take that as a no for now. Let me know if you guys reconsider. I'll see how far we get utilizing absolute values. I'm just worried that we'll find ourselves having to do very different configurations for services that are called very different volumes.

**Comment by Sirupsen** [comment]
Why do you think the configuration would be different? We use the same between MySQL shards that take 10,000s of queries per second and services that do few requests per minute. Works great.

**Comment by smitchelus** [comment]
That's interesting Simon as that's exactly the type of scenario I was worried would require very different configurations when using absolute values (although at this point we're planning on only using this for various HTTP based services not the database connection itself). If you don't mind can I ask what your configuration looks like?

**Comment by Sirupsen** [comment]
Absolutely. For MySQL shards we use this configuration:

```yaml
semian: &semian
  tickets: <%= Resiliency.semian_ticket_count %>
  timeout: <%= Resiliency.semian_ticket_timeout %>
  success_threshold: 2
  error_threshold: 3
  error_timeout: 10
```

`Resiliency.semian_ticket_count` is defined as the number of Unicorn or job workers on the box divided by two. We generally run around 48 workers per box, that's around 3 per core.

`Resiliency.semian_ticket_timeout` is `2s` for job workers, and `0s` for web workers. The difference between a ticket count and a timeout is that timeouts will allow short bursts on a resource, whereas ticket counts is the absolute maximum concurrency. This is a problem for job workers with our workload, but not for web workers.

With this configuration we run over a dozen shards with 10,000+ workers without issues. A single shard outage never has an impact on the latency of the entire platform. MySQL, given our throughput to it, is _by_ far the biggest threat.

As for HTTP based services, we do very low throughput to them. This means that bulkheads are not really useful. Circuit breakers are quite useful though. For HTTP services our configuration looks like this:

```
SEMIAN_PARAMETERS = {                                                                                                                               
  tickets: 1000,                                                                                                                                    
  success_threshold: 1,                                                                                                                             
  error_threshold: 3,                                                                                                                               
  error_timeout: 20                                                                                                                                 
}.freeze 
```

This effectively disabled bulkheads for them because we do low throughput to them (https://github.com/Shopify/semian/pull/89 allows just disabling them). It's fairly hard to reason about good ticket counts for them, and we don't see a scenario where it'd be a huge issue. It'll take a while for all the circuits to trigger, but given the throughput spending that capacity waiting for the timeouts is not really an issue as long as we converge towards failing fast.

So they're not actually exactly the same, but the circuit breaker thresholds don't matter too much in our experience for these low latency services. We're much more concerned about the high throughput resources (MySQL, basically) than anything else.

**Comment by smitchelus** [comment]
Thanks so much for sharing this! We will experiment with a variation of this for our candidate services. I appreciate your insight!

**Comment by Sirupsen** [comment]
Absolutely! Let me know if you have other issues.

Another thing I'd love to see in core Semian is that HTTP can be circuit broken by default, intead of ad-hoc configuring every endpoint. The reason it's not is because if you talk to 10,000s of hosts like we do, you'd allocate way too many circuit breakers. The implementation needs to have a ring-buffer scoped by resource for that to not be a subtle memory leak. If you have similar issues, let me know.
